[package]
name = "test_utils"
authors = ["Mysten Labs <build@mystenlabs.com>"]
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
tokio = { version = "1.18.2", features = ["sync", "rt"] }
tokio-util = { version = "0.7.2", features = ["codec"] }
bytes = "1.1.0"
futures = "0.3.21"
async-trait = "0.1.53"
rand = "0.8.5"
rocksdb = "0.18.0"
tracing = { version = "0.1.34", features = ["log"] }
tempfile = "3.3.0"
bcs = "0.1.3"

sui-adapter = { path = "../sui_programmability/adapter" }
sui-framework = { path = "../sui_programmability/framework" }
move-package = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b" }
move-core-types = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b", features = ["address20"] }
typed-store = { git = "https://github.com/MystenLabs/mysten-infra", rev ="7c247967e5a5abd59ecaa75bc62b05bcdf4503fe"}
narwhal-config = { git = "https://github.com/MystenLabs/narwhal", rev = "23745f48103656eae4a4205d0b3edd53ad8894de", package = "config" }

sui-config = { path = "../crates/sui-config" }
sui-types = { path = "../sui_types" }
sui_core = { path = "../sui_core" }
sui-network = { path = "../crates/sui-network" }
sui = { path = "../sui" }
