[package]
name = "sui"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
rayon = "1.5.1"
anyhow = "1.0.55"
bytes = "1.1.0"
futures = "0.3.21"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
structopt = "0.3.26"
tempfile = "3.3.0"
tokio = { version = "1.17.0", features = ["full"] }
rand = "0.8.4"
toml = "0.5.8"
strum = "0.24.0"
strum_macros = "0.24.0"
num_cpus = "1.13.1"
base64 = "0.13.0"
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"] }
rocksdb = "0.18.0"
hex = "0.4.3"
async-trait = "0.1.52"
serde_with = { version = "1.12.0", features = ["hex"] }
tracing = { version = "0.1.31", features = ["log"] }
tracing-subscriber = { version = "0.3.9", features = ["time", "registry", "env-filter"] }
serde-value = "0.7.0"
serde-name = "0.2.0"
log = "0.4.14"
dirs = "4.0.0"
clap = { version = "3", features = ["derive"] }
telemetry_subscribers = { git = "https://github.com/MystenLabs/mysten-infra", rev = "a45af6dc28aa12c8cc13521d118c24aadd4c6adf" }

bcs = "0.1.3"
sui_core = { path = "../sui_core" }
sui-adapter = { path = "../sui_programmability/adapter" }
sui-framework = { path = "../sui_programmability/framework" }
sui-network = { path = "../network_utils" }
sui-types = { path = "../sui_types" }

rustyline = "9.1.2"
rustyline-derive = "0.6.0"
colored = "2.0.0"
unescape = "0.1.0"

# Deps for rest server
dropshot = "0.7.0"
http = "0.2.6"
hyper = "0.14.17"
schemars = "0.8.8"

move-package = { git = "https://github.com/diem/move", rev = "63bd52e0f5b02711d29a678e6f946b3d429f2090" }
move-core-types = { git = "https://github.com/diem/move", rev = "63bd52e0f5b02711d29a678e6f946b3d429f2090", features = ["address20"] }
move-bytecode-verifier = { git = "https://github.com/diem/move", rev = "63bd52e0f5b02711d29a678e6f946b3d429f2090" }
move-binary-format = { git = "https://github.com/diem/move", rev = "63bd52e0f5b02711d29a678e6f946b3d429f2090" }
move-bytecode-utils = { git = "https://github.com/diem/move", rev = "63bd52e0f5b02711d29a678e6f946b3d429f2090" }
move-unit-test = { git = "https://github.com/diem/move", rev = "63bd52e0f5b02711d29a678e6f946b3d429f2090" }

once_cell = "1.9.0"
reqwest = { version = "0.11.10", features=["json","serde_json", "blocking"]}

[dev-dependencies]
tracing-test = "0.2.1"

[[bin]]
name = "microbench"
path = "src/microbench.rs"

[[bin]]
name = "microbench_latency"
path = "src/microbench_latency.rs"

[[bin]]
name = "wallet"
path = "src/wallet.rs"

[[bin]]
name = "sui"
path = "src/sui.rs"

[[bin]]
name = "sui-move"
path = "src/sui-move.rs"

[[bin]]
name = "rest_server"
path = "src/rest_server.rs"
