[package]
name = "sui-faucet"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = { version = "1.0.58", features = ["backtrace"] }
async-trait = "0.1.53"
axum = "0.5.11"
clap = { version = "3.1.17", features = ["derive"] }
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
tracing = "0.1.35"
serde = { version = "1.0.138", features = ["derive"] }
tower = { version = "0.4.12", features = ["util", "timeout", "load-shed", "limit"] }
tower-http = { version = "0.3.4", features = ["cors"] }
http = { version = "0.2.8" }

sui = { path = "../sui" }
sui-json-rpc-api = { path = "../sui-json-rpc-api" }
sui-types = { path = "../sui-types" }
sui-config = { path = "../sui-config" }
telemetry-subscribers = { git = "https://github.com/MystenLabs/mysten-infra", rev = "7ce3f9bba93c93d87d02ec921ce7312c6f6dd0c4" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
test-utils = { path = "../test-utils" }

[[bin]]
name = "sui-faucet"
path = "src/main.rs"
