[package]
name = "sui-network"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
async-trait = "0.1.53"
tonic = "0.7"

sui-types = { path = "../sui-types" }

mysten-network = { git = "https://github.com/MystenLabs/mysten-infra", rev = "7ce3f9bba93c93d87d02ec921ce7312c6f6dd0c4" }
workspace-hack = { path = "../workspace-hack"}

[build-dependencies]
tonic-build = { git = "https://github.com/hyperium/tonic.git", rev = "de2e4ac077c076736dc451f3415ea7da1a61a560", default-features = false, features = [ "transport" ] }
